# Generated by Django 2.2.12 on 2022-03-18 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder', models.CharField(blank=True, max_length=20, verbose_name='Workorder')),
                ('date', models.DateTimeField(verbose_name='Time In')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Description')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('budget', models.IntegerField(blank=True, verbose_name='Budget')),
                ('quoted_price', models.IntegerField(blank=True, verbose_name='Quoted Price')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorder_contact', to='customer.Contact')),
                ('material', models.ManyToManyField(to='inventory.Inventory')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorder_customer', to='customer.Customer')),
            ],
        ),
    ]
