# Generated by Django 2.2.12 on 2022-03-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Deadline'),
        ),
    ]
