# Generated by Django 2.2.12 on 2022-03-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_auto_20220319_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='quoted_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quoted Price'),
        ),
    ]
