# Generated by Django 2.2.12 on 2022-03-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0004_auto_20220319_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='workorder',
            field=models.CharField(max_length=20, verbose_name='Workorder'),
        ),
    ]
