# Generated by Django 2.2.12 on 2022-03-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0005_auto_20220319_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Time In'),
        ),
    ]
