# Generated by Django 2.2.12 on 2022-03-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0009_auto_20220321_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Time In'),
        ),
    ]
