# Generated by Django 2.2.12 on 2022-03-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0010_auto_20220321_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(null=True, verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
    ]
