# Generated by Django 2.2.12 on 2022-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0012_auto_20220321_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(null=True, verbose_name='Time In'),
        ),
    ]
