# Generated by Django 2.2.12 on 2022-03-18 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address1', models.CharField(blank=True, max_length=100, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, verbose_name='Adddress 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=100, verbose_name='Zipcode')),
                ('phone1', models.CharField(blank=True, max_length=100, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=100, verbose_name='Phone 2')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=100, verbose_name='Website')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('lname', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('phone1', models.CharField(blank=True, max_length=100, verbose_name='Phone 1')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
