# Generated by Django 2.2.12 on 2022-03-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_part_number', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('qty_ordered', models.IntegerField(blank=True)),
                ('cost', models.IntegerField(blank=True)),
                ('qty_sold', models.IntegerField(blank=True)),
                ('sell_price', models.IntegerField(blank=True)),
                ('total', models.IntegerField(blank=True)),
            ],
        ),
    ]
